adminapp/urls.py
import adminapp.views as adminapp
from django.urls import path

app_name = 'adminapp'

urlpatterns = [
    path('users/create/', adminapp.user_create, name='user_create'),
    path('users/read/', adminapp.UsersListView.as_view(), name='users'),
    path('users/update/<int:pk>/', adminapp.user_update, name='user_update'),
    path('users/delete/<int:pk>/', adminapp.user_delete, name='user_delete'),

    path('categories/create/', adminapp.ProductCategoryCreateView.as_view(), name='category_create'),
    path('categories/read/', adminapp.categories, name='categories'),
    path('categories/update/<int:pk>/', adminapp.ProductCategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', adminapp.ProductCategoryDeleteView.as_view(), name='category_delete'),

    path('products/create/category/<int:pk>/', adminapp.product_create, name='product_create'),
    path('products/read/category/<int:pk>/', adminapp.products, name='products'),
    path('products/read/<int:pk>/', adminapp.ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', adminapp.product_update, name='product_update'),
    path('products/delete/<int:pk>/', adminapp.product_delete, name='product_delete'),
]

authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
import mainapp.views as mainapp
import authapp.views as authapp
import ordersapp.views as ordersapp
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:

    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', cache_page(3600)(mainapp.products)),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('category/<int:pk>/', mainapp.products, name='category'),
]

ordersapp/urls.py
from django.urls import re_path
import ordersapp.views as ordersapp

import ordersapp.views as ordersapp

app_name = 'ordersapp'

urlpatterns = [
    re_path(r'^$', ordersapp.OrderList.as_view(), name='orders_list'),
    re_path(r'^forming/complete/(?P<pk>\d+)/$', ordersapp.order_forming_complete, name='order_forming_complete'),
    re_path(r'^create/$', ordersapp.OrderItemsCreate.as_view(), name='order_create'),
    re_path(r'^read/(?P<pk>\d+)/$', ordersapp.OrderRead.as_view(), name='order_read'),
    re_path(r'^update/(?P<pk>\d+)/$', ordersapp.OrderItemsUpdate.as_view(), name='order_update'),
    re_path(r'^delete/(?P<pk>\d+)/$', ordersapp.OrderDelete.as_view(), name='order_delete'),
    re_path(r'^product/(?P<pk>\d+)/price/$', ordersapp.get_product_price)
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание катергории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = "Продукты"

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import ProductCategory, Product
from basketapp.models import Basket
import random, os
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
# частичное кэширование с помощью ajax
from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse

from django.views.decorators.cache import never_cache

JSON_PATH = 'mainapp/json'

links_main_menu = [
{
    'href': 'main', 'name': 'Главная'
},
{
    'href': 'products:index', 'name': 'Каталог'
},
{
    'href': 'contact', 'name': 'Контакты'
}
]


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def main(request):
    title = 'главная'
    user_name = request.user

    context = {
        'title': title,
        'links_main_menu': links_main_menu,
        'user_name': user_name
    }

    return render(request, 'mainapp/index.html', context)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(is_active=True, category__is_active=True,category=hot_product.category).exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products


def products(request, pk=None, page=1):
    title = "продукты"
    links_menu = get_links_menu()
    user_name = request.user

    product_list = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')

    if pk is not None:
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = get_products_orederd_by_price()

        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_main_menu': links_main_menu,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'user_name': user_name
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'links_main_menu': links_main_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'user_name': user_name
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'
    user_name = request.user
    links_menu = get_links_menu()
    product = get_product(pk)

    content = {
        'title': title,
        'links_main_menu': links_main_menu,
        'links_menu': links_menu,
        'product': product,
        'basket': get_basket(request.user),
        'user_name': user_name,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = "контакты"
    user_name = request.user

    # if settings.LOW_CACHE:
    #     key = f'locations'
    #     locations = cache.get(key)
    #     if locations is None:
    #         locations = load_from_json('contact__locations')
    #         cache.set(key, locations)
    # else:
    #     locations = load_from_json('contact__locations')

    context = {
        'title': title,
        'links_main_menu': links_main_menu,
        'user_name': user_name,
        # 'locations': locations,
    }

    return render(request, 'mainapp/contact.html', context)


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_orederd_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_orederd_by_price(pk)

            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }

            result = render_to_string('mainapp/includes/inc_products_list_content.html', context=content, request=request)

            return JsonResponse({'result': result})


# def load_from_json(file_name):
#     with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
#         return json.load(infile)

mainapp/templates/mainapp/includes/inc_categories_menu.html
<ul class="links-menu">
  <li>
    <a href="{% url 'products:index' %}"
       class="{% if request.resolver_match.view_name == 'products:index' %}
                active_main_menu
              {% else %}
                header_a
              {% endif %}">

      Категории

    </a>
  </li>

  <li>
    <a href="{% url 'products:category' 0 %}"
       class="{% if request.resolver_match.kwargs.pk == 0 %}
                active_main_menu
              {% else %}
                header_a
              {% endif %}">

      Все

    </a>
  </li>

  {% for link in links_menu %}

    <li>
      <a href="{% url 'products:category' link.pk %}"
         class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}
                  active_main_menu
                {% else %}
                  header_a
                {% endif %}">

        {{ link.name }}

      </a>
    </li>

  {% endfor %}

</ul>

mainapp/templates/mainapp/includes/inc_main_menu.html
{% load static %}

<div class="header">
  <span class="logo">
    <a href="{% url 'main' %}"><img class="img_logo" src="{% static 'img/hit.jpg' %}"  alt="Лого"></a>
  </span>
  <div class="menu">
    <ul class="header_ul">

  {% if user.is_authenticated %}

    <li>
      <div class="dropdown">
        <a href="{% url 'auth:edit' %}"
               class="{% if request.resolver_match.url_name == 'categories' or category.name %}
                        active_main_menu{% else %}header_a
                      {% endif %}" data-toggle="dropdown">

          {{ user.first_name|default:'Пользователь' }}

          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <li>
            <a href="{% url 'auth:edit' %}">профиль</a>
          </li>
          <li>
            <a href="{% url 'ordersapp:orders_list' %}">заказы</a>
          </li>
        </ul>
      </div>
    </li>

  {% endif %}

  {% if user.is_superuser %}

    <li>
      <a href="{% url 'admin:users' %}"
             class="{% if request.resolver_match.url_name == 'categories' or category.name %}
                      active_main_menu{% else %}header_a
                    {% endif %}">админка</a>
    </li>

  {% endif %}

  <li>

    {% if user.is_authenticated %}

      <a href="{% url 'auth:logout' %}">выйти</a>

    {% else %}

      <a href="{% url 'auth:login' %}">войти</a>

    {% endif %}

  </li>

      {% for item in links_main_menu %}

        <li><a class="{% if request.resolver_match.view_name == item.href %}active_main_menu{% else %}header_a{% endif %}" href="{% url item.href %}">{{ item.name }}</a></li>

      {% endfor %}

    </ul>
  </div>
  <a href="#" class="search"></a>
  <a href="{% url 'basket:view' %}" class="header_a">
  <span>

    {% if basket %}

      {{ basket.0.total_cost|floatformat:0 }} руб

      ({{ basket.0.total_quantity }} шт)

    {% endif %}

  </span>
  </a>
</div>

mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load staticfiles %}

<div class="links clearfix">

  {% include 'mainapp/includes/inc_categories_menu.html' %}

</div>

<div class="products_list">
  <div class="title clearfix">

    <h2>Категория: "{{ category.name|title }}"</h2>

    <div class="paginator">

      {% if products.has_previous %}

        <a href="{% url 'products:page' category.pk products.previous_page_number %}"> < </a>

      {% endif %}

      <span class="current">

        страница {{ products.number }} из {{ products.paginator.num_pages }}

      </span>

      {% if products.has_next %}

        <a href="{% url 'products:page' category.pk products.next_page_number %}"> > </a>

      {% endif %}

    </div>
  </div>
  <div class="category-products clearfix">

    {% for product in products %}

      <div class="block">
        <a href="{% url 'products:product' product.pk %}">
        <img src="/media/products_images/{{ product.image }}" alt="{{ product.short_desc }}">
        <div class="text">
          <img src="{% static 'img/icon-hover.png' %}" alt="hover">

          <h4>{{ product.name }}</h4>

          {% for item in basket %}
            {% if item.product == product %}

            <div>{{ item.quantity }}</div>

            {% endif %}
            {% endfor %}

          <p>{{ product.description }}</p>

          <a href="{% url 'products:product' product.pk %}">Добавить в корзину</a>
          <br>
          <a href="{% url 'basket:remove' product.pk %}">Удалить из корзины</a>
        </div>
        </a>
      </div>

    {% endfor %}

  </div>
</div>