authapp/urls.py
from django.urls import path, re_path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),
    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path

import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit')
]

geekshop/urls.py
import mainapp.views as mainapp
import authapp.views as authapp
import ordersapp.views as ordersapp
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include

from django.conf import settings
from django.conf.urls.static import static

import debug_toolbar

urlpatterns = [
    path('', mainapp.main, name='main'),
    path('basket/', include('basketapp.urls', namespace='basket')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('products/', include('mainapp.urls', namespace='products')),
    path('contact/', mainapp.contact, name='contact'),
    path('admin/', include('adminapp.urls', namespace='admin')),
    path('', include('social_django.urls', namespace='social')),
    path('order/', include('ordersapp.urls', namespace='order')),
]

if settings.DEBUG:

    urlpatterns += path('__debug__/', include(debug_toolbar.urls)),

mainapp/urls.py
from django.urls import path, re_path
from django.views.decorators.cache import cache_page

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp.products, name='index'),
    re_path(r'^category/(?P<pk>\d+)/$', cache_page(3600)(mainapp.products)),
    re_path(r'^category/(?P<pk>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
    re_path(r'^category/(?P<pk>\d+)/page/(?P<page>\d+)/ajax/$', cache_page(3600)(mainapp.products_ajax)),
    path('product/<int:pk>/', mainapp.product, name='product'),
    path('category/<int:pk>/', mainapp.products, name='category'),
]

mainapp/models.py
from django.db import models

class ProductCategory(models.Model):
    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = "Категории"

    name = models.CharField(verbose_name='имя', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание катергории', blank=True)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = "Продукты"

    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(verbose_name='активна', default=True)

    def __str__(self):
        return "{} ({})".format(self.name, self.category.name)

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .models import ProductCategory, Product
from basketapp.models import Basket
import random, os
from django.conf import settings
from django.core.cache import cache
from django.views.decorators.cache import cache_page
# частичное кэширование с помощью ajax
from django.template.loader import render_to_string
from django.views.decorators.cache import cache_page
from django.http import JsonResponse

from django.views.decorators.cache import never_cache

JSON_PATH = 'mainapp/json'

links_main_menu = [
{
    'href': 'main', 'name': 'Главная'
},
{
    'href': 'products:index', 'name': 'Каталог'
},
{
    'href': 'contact', 'name': 'Контакты'
}
]


def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_orederd_by_price():
    if settings.LOW_CACHE:
        key = 'products_orederd_by_price'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_orederd_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_orederd_by_price_{pk}'
        products = cache.get(key)
        if products is None:
            products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')
            cache.set(key, products)
        return products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')


def main(request):
    title = 'главная'
    user_name = request.user

    context = {
        'title': title,
        'links_main_menu': links_main_menu,
        'user_name': user_name
    }

    return render(request, 'mainapp/index.html', context)


def get_basket(user):
    if user.is_authenticated:
        return Basket.objects.filter(user=user)
    else:
        return []


def get_hot_product():
    products = get_products()

    return random.sample(list(products), 1)[0]


def get_same_products(hot_product):
    same_products = Product.objects.filter(is_active=True, category__is_active=True,category=hot_product.category).exclude(pk=hot_product.pk).select_related('category')[:3]

    return same_products


def products(request, pk=None, page=1):
    title = "продукты"
    links_menu = get_links_menu()
    user_name = request.user

    product_list = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')

    if pk is not None:
        if pk == 0:
            category = {'pk': 0, 'name': 'все'}
            products = get_products_orederd_by_price()

        else:
            category = get_category(pk)
            products = get_products_in_category_orederd_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        content = {
            'title': title,
            'links_main_menu': links_main_menu,
            'links_menu': links_menu,
            'category': category,
            'products': products_paginator,
            'user_name': user_name
        }

        return render(request, 'mainapp/products_list.html', content)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'links_main_menu': links_main_menu,
        'hot_product': hot_product,
        'same_products': same_products,
        'user_name': user_name
    }

    return render(request, 'mainapp/products.html', content)


def product(request, pk):
    title = 'продукты'
    user_name = request.user
    links_menu = get_links_menu()
    product = get_product(pk)

    content = {
        'title': title,
        'links_main_menu': links_main_menu,
        'links_menu': links_menu,
        'product': product,
        'basket': get_basket(request.user),
        'user_name': user_name,
    }
    return render(request, 'mainapp/product.html', content)


def contact(request):
    title = "контакты"
    user_name = request.user

    # if settings.LOW_CACHE:
    #     key = f'locations'
    #     locations = cache.get(key)
    #     if locations is None:
    #         locations = load_from_json('contact__locations')
    #         cache.set(key, locations)
    # else:
    #     locations = load_from_json('contact__locations')

    context = {
        'title': title,
        'links_main_menu': links_main_menu,
        'user_name': user_name,
        # 'locations': locations,
    }

    return render(request, 'mainapp/contact.html', context)


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        links_menu = get_links_menu()

        if pk:
            if pk == '0':
                category = {
                    'pk': 0,
                    'name': 'все'
                }
                products = get_products_orederd_by_price()
            else:
                category = get_category(pk)
                products = get_products_in_category_orederd_by_price(pk)

            paginator = Paginator(products, 2)
            try:
                products_paginator = paginator.page(page)
            except PageNotAnInteger:
                products_paginator = paginator.page(1)
            except EmptyPage:
                products_paginator = paginator.page(paginator.num_pages)

            content = {
                'links_menu': links_menu,
                'category': category,
                'products': products_paginator,
            }

            result = render_to_string('mainapp/includes/inc_products_list_content.html', context=content, request=request)

            return JsonResponse({'result': result})


# def load_from_json(file_name):
#     with open(os.path.join(JSON_PATH, file_name + '.json'), 'r', errors='ignore') as infile:
#         return json.load(infile)

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="UTF-8">
  <title>

    {% block title %}
      Интернет магазин|{{ title|title }}
    {% endblock %}

  </title>

  {% block css %}

    <link rel="stylesheet" type="text/css" href="{% static '/css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">

  {% endblock %}


</head>
  <body>
    <div class="container">

      {% block menu %}
        {% include 'mainapp/includes/inc_main_menu.html' %}
      {% endblock %}

      <div class="content">
        {% block content %}

        {% endblock %}
      </div>

      {% block footer %}

        <div class="footer">
          <div><a class="back_button" href="#">Наверх!</a></div>
          <p class="copyright">Все права защищены&copy;</p>
        </div>

      {% endblock %}

      {% block js %}

        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main_scripts.js' %}"></script>

      {% endblock %}
    </div>
  </body>
</html>

mainapp/templates/mainapp/contact.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<form class="form">
  <legend><h2>Обратная связь:</h2></legend>
  <p><input type="text" placeholder="Введите Ваше имя" size="50" class="form_input"> </p>
  <p><input type="email" placeholder="Введи ваш Email" size="50" class="input_email"> </p>
  <p>
    <input type="text" placeholder="Напишите тему" size="50" class="form_input"><br>
    <input type="checkbox" checked> Хочу получить информацию по акциям и скидкам!
  </p>
  <p><textarea placeholder="Введите комментарий" class="contact_form_textarea"></textarea></p>
  <input type="submit" value="Отправить" class="contact_buttons">
  <input type="reset" value="Очистить" class="contact_buttons">
</form>
<div>
  <h3>Санкт-Петербург:</h3>
  <p> Адрес: Ленина, д.1</p>
  <p> Телефон: +7 (812) 1234567</p>
  <p> E-mail: email@bestseller.ru </p>
<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?um=constructor%3Af2ad791cebb7df1c5b3f7ca1e7fa27af3995bcaef48cad4db438bd2428d84f7a&amp;width=787&amp;height=418&amp;lang=ru_RU&amp;scroll=true"></script>

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

<h3>Приветствую Вас, посетитель нашего магазина "ХитПродаж"</h3>
<p>Не забудьте посмотреть <a href="{% url links_main_menu.1.href %}">каталог товаров</a></p>
{% for product in products %}
  <div class="block">
    <a href="#">
      <img src="/media/{{ product.image }}" alt="{{ product.short_desc }}">
      <div class="text">
        <h3>{{ product.category.name }}</h3>
        <h4>{{ product.name }}</h4>
        <p>{{ product.description }}</p>
      </div>
    </a>
  </div>
{% endfor %}


{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}
  <div class="details">
    <div class="links clearfix">
      {% include 'mainapp/includes/inc_categories_menu.html' %}
    </div>

    <div class="details-products">
      <div class="details-slider">
        <div class="slider-product">
          <img src="/media/products_images/{{ product.image }}"
               alt="{{ product.short_desc }}">
        </div>
        <div class="slider-control">
          <div class="block">
            <a href="#">
              <img src="/media/products_images/{{ product.image }}" alt="вариант 1">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/products_images/{{ product.image }}" alt="вариант 2">
            </a>
          </div>
          <div class="block">
            <a href="#">
              <img src="/media/products_images/{{ product.image }}" alt="вариант 3">
            </a>
          </div>
        </div>
      </div>

      <div class="description">
        <h3 class="big-bold">{{ product.name }}</h3>
        <br>
        <p class="price"> {{ product.price }} <span>руб</span></p>
        <a href="{% url 'basket:add' product.pk %}" class="red-button">
          заказать
          <i class="fa fa-chevron-right" aria-hidden="true"></i>
        </a>
        <div class="description-text">
          {{ product.description }}
        </div>
      </div>
    </div>

  </div>

  <div class="clr"></div>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

  {% include 'mainapp/includes/inc_categories_menu.html' %}

    <div class="details-products">
      <div class="details-slider">
          <div class="slider-product">
            <img src="/media/products_images/{{ hot_product.image }}">
          </div>
          <div class="slider-control">
            <div class="block">
              <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt=""></a>
            </div>
            <div class="block">
              <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt=""></a>
            </div>
            <div class="block">
              <a href="#"><img src="/media/products_images/{{ hot_product.image }}" alt=""></a>
            </div>
          </div>
        </div>

        <div class="description">

          <h3 class="big-bold">{{ hot_product.name }}</h3>

          <h3 class="red">горячее предложение</h3>
          <p class="price">{{ hot_product.price }} <span>руб</span></p>
          <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
            заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
          </a>
          <div class="description-text">

            {{ hot_product.description }}

          </div>
      </div>
  </div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block content %}

  <div class="details">
    {% include 'mainapp/includes/inc_products_list_content.html' %}
  </div>

    <div class="clr"></div>

{% endblock %}